name: iot

prometheus:
  image: prom/prometheus
  tag: v2.27.1
  externalPort: 30283
  dataStorageSize: 2.5Gi
  rulesStorageSize: 2.5Gi
  url: prometheus.iot

alertmanager:
  image: prom/alertmanager
  tag: v0.22.1
  externalPort: 30284
  dataStorageSize: 2.5Gi
  url: alertmanager.iot

grafana:
  image: grafana/grafana
  tag: 7.5.7
  externalPort: 30285
  dataStorageSize: 5Gi
  url: dashboard.iot

mosquitto:
  image: eclipse-mosquitto
  tag: 2.0.10
  externalPort: 31883
  dataStorageSize: 2.5Gi
  authStorageSize: 100Mi
