apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "fullname" . }}-metrics
  name: {{ include "fullname" . }}-alertmanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "fullname" . }}-alertmanager
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --web.external-url=http://{{ .Values.alertmanager.url }}
          image: {{ .Values.alertmanager.image }}:{{ .Values.alertmanager.tag }}
          ports:
            - containerPort: 9093
              name: alertm-port
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: '/'
              port: 9093
              scheme: 'HTTP'
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/alertmanager
              name: {{ include "fullname" . }}-alertmanager-config
            - mountPath: /alertmanager
              name: {{ include "fullname" . }}-alertmanager-data
      volumes:
        - name: {{ include "fullname" . }}-alertmanager-config
          secret:
            secretName: {{ include "fullname" . }}-alertmanager-config
        - name: {{ include "fullname" . }}-alertmanager-data
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-alertmanager-data-pvc
      restartPolicy: Always
