apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: alertmanager-port
      port: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
