apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-alertmanager-config
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'smtp.duke.edu:465'
      smtp_from: '{{ .Release.Namespace }}-alertmanager@duke.edu'
    route:
      receiver: 'admin'
      group_by: ['miqTarget']
      group_wait: 30s
      repeat_interval: 3h
    receivers:
      - name: 'admin'
        email_configs:
        {{- range .Values.alert_admin_emails }}
          - to: {{ . | quote }}
        {{- end }}
