apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: grafana-port
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: {{ .Values.grafana.externalPort }}
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
