apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.prometheus.url }}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: {{ include "fullname" . }}-prometheus
            port: 
              number: 9090
  - host: {{ .Values.alertmanager.url }}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: {{ include "fullname" . }}-alertmanager
            port:
              number: 9093
  - host: {{ .Values.grafana.url }}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: {{ include "fullname" . }}-grafana
            port:
              number: 3000
  - host: {{ .Values.mosquitto.url }}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: {{ include "fullname" . }}-mosquitto
            port:
              number: 1883
