apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: prometheus-port
      port: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
