apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-prometheus
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: prometheus-port
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: {{ .Values.prometheus.externalPort }}
  selector:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
