apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fullname" . }}-scrape-view-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "fullname" . }}-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ include "fullname" . }}-viewer
  namespace: {{ .Release.Namespace }}
